require 'test/unit'
require_relative '../test/tc_parser'
require_relative '../test/tc_patterns'
require_relative '../test/tc_partyconfig'
require_relative '../test/tc_analyzer'
require_relative '../test/tc_accumulator'
