:logs:
  :level:       0
  :stdout:      true
  :filename:    cloudmoogle.log
:aws:
  :sqs:
    :queue:       cloudmoogle-analysis
  :s3:
    :analysis_bucket:  cloudmoogle-analysis
    :data_bucket:      cloudmoogle-data
:db:
  :party_configs:
    :connector:   DynamoDB
    :table:       cloudmoogle-parties
  :events:
    :connector:   DynamoDB
    :table:       cloudmoogle-events
